### training settings ###
seed: 42
phase: train

### dataset settings ###
dataset_name: bdd100k

# for dataset
dataroot: /fs1/groups1/gaa50131/user/nakashima/datasets/bdd100k/seg
image_preprocess: scalewidth_crop
label_preprocess: scalewidth_crop
load_size: 1280
crop_size: 720
aspect_ratio: 0.5625
num_classes: 19

# for dataloader
batch_size: 8
val_batch_size: 32
batches_per_allreduce: 1
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
num_workers: 1


### DDP settings ###
use_adasum: False
fp16_allreduce: False


### training loop settings ###
epochs: 50
warmup_epochs: 5
validation: False


### model settings ###
model_name: deeplabv3_r50
imgnet_pretrained: True
ckpt_pth: null
transfer_learning: False
norm_type: syncbatch
use_fp16: False


### optimizer settings ###
lr: 1e-3
momentum: 0.95
weight_decay: 5e-4
decay_epoch_freq: 25


### visualization settings ###
group: segmentation
log_loss_freq: 500
log_visual_freq: 3450
save_epoch_freq: 10


# for continue train
continue_train: False
which_epoch: 1
name: null
id: null
